<?php
if (!defined('ABSPATH')) { exit; }

/**
 * Goal.com Style Matches Widget
 * Features: Date slider, competition filter, circular score badges, responsive design
 */
class Sawah_Sports_Widget_Goal_Style_Matches extends \Elementor\Widget_Base {

    public function get_name() { 
        return 'sawah_sports_goal_matches'; 
    }

    public function get_title() { 
        return __('Matches - Goal Style', 'sawah-sports'); 
    }

    public function get_icon() { 
        return 'eicon-posts-ticker'; 
    }

    public function get_categories() { 
        return ['sawah-sport']; 
    }

    protected function register_controls() {
        $this->start_controls_section('content', [
            'label' => __('Settings', 'sawah-sports'),
            'tab' => \Elementor\Controls_Manager::TAB_CONTENT,
        ]);

        $this->add_control('widget_title', [
            'label' => __('Widget Title', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::TEXT,
            'default' => '',
            'description' => __('Leave empty to hide title', 'sawah-sports'),
        ]);

        $this->add_control('date_range_days', [
            'label' => __('Date Range (Days)', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::NUMBER,
            'default' => 7,
            'min' => 3,
            'max' => 14,
            'description' => __('Number of days to show in date slider (3 before today, 3 after)', 'sawah-sports'),
        ]);

        $this->add_control('cyprus_priority', [
            'label' => __('Cyprus League Priority', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::SWITCHER,
            'default' => 'yes',
            'description' => __('Show Cyprus matches first', 'sawah-sports'),
        ]);

        $this->add_control('show_competition_filter', [
            'label' => __('Show Competition Filter', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::SWITCHER,
            'default' => 'yes',
        ]);

        $this->add_control('auto_refresh', [
            'label' => __('Auto Refresh (seconds)', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::NUMBER,
            'default' => 30,
            'min' => 0,
            'max' => 300,
            'description' => __('Auto refresh interval for live matches (0 to disable)', 'sawah-sports'),
        ]);

        $this->end_controls_section();

        // Style Section
        $this->start_controls_section('style_section', [
            'label' => __('Style', 'sawah-sports'),
            'tab' => \Elementor\Controls_Manager::TAB_STYLE,
        ]);

        $this->add_control('primary_color', [
            'label' => __('Primary Color', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::COLOR,
            'default' => '#000000',
        ]);

        $this->add_control('accent_color', [
            'label' => __('Accent Color', 'sawah-sports'),
            'type' => \Elementor\Controls_Manager::COLOR,
            'default' => '#fbbf24',
        ]);

        $this->end_controls_section();
    }

    protected function render() {
        $settings = $this->get_settings_for_display();
        $widget_id = $this->get_id();
        ?>
        <div id="ss-goal-matches-<?php echo esc_attr($widget_id); ?>" 
             class="ss-widget ss-goal-matches"
             data-cyprus-priority="<?php echo esc_attr($settings['cyprus_priority']); ?>"
             data-auto-refresh="<?php echo esc_attr($settings['auto_refresh']); ?>"
             data-primary-color="<?php echo esc_attr($settings['primary_color']); ?>"
             data-accent-color="<?php echo esc_attr($settings['accent_color']); ?>">
            
            <?php if (!empty($settings['widget_title'])) : ?>
                <div class="ss-goal-header">
                    <h2><?php echo esc_html($settings['widget_title']); ?></h2>
                </div>
            <?php endif; ?>

            <!-- Competition Filter -->
            <?php if ($settings['show_competition_filter'] === 'yes') : ?>
            <div class="ss-goal-filters">
                <div class="ss-goal-competition-select">
                    <select class="ss-goal-comp-dropdown">
                        <option value="all"><?php echo esc_html__('Όλες οι διοργανώσεις', 'sawah-sports'); ?></option>
                    </select>
                    <i class="eicon-chevron-down"></i>
                </div>
            </div>
            <?php endif; ?>

            <!-- Date Slider -->
            <div class="ss-goal-date-wrapper">
                <button class="ss-goal-date-nav ss-goal-prev" aria-label="Previous">
                    <i class="eicon-chevron-left"></i>
                </button>
                <div class="ss-goal-date-slider">
                    <!-- Dates will be generated by JS -->
                </div>
                <button class="ss-goal-date-nav ss-goal-next" aria-label="Next">
                    <i class="eicon-chevron-right"></i>
                </button>
            </div>

            <!-- Matches Container -->
            <div class="ss-goal-matches-container">
                <div class="ss-goal-loading">
                    <div class="ss-goal-spinner"></div>
                    <p><?php echo esc_html__('Φόρτωση αγώνων...', 'sawah-sports'); ?></p>
                </div>
            </div>
        </div>
        <?php
    }
}